//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.BulletedList tabs;
		
		protected System.Web.UI.WebControls.MultiView multiview;
		
		protected System.Web.UI.WebControls.View aba1;
		
		protected System.Web.UI.WebControls.HiddenField id;
		
		protected System.Web.UI.WebControls.TextBox nome;
		
		protected System.Web.UI.WebControls.TextBox cpf;
		
		protected System.Web.UI.WebControls.TextBox cep;
		
		protected System.Web.UI.WebControls.TextBox cidade;
		
		protected System.Web.UI.WebControls.TextBox bairro;
		
		protected System.Web.UI.WebControls.TextBox rua;
		
		protected System.Web.UI.WebControls.TextBox uf;
		
		protected System.Web.UI.WebControls.TextBox numero;
		
		protected System.Web.UI.WebControls.CheckBox check;
		
		protected System.Web.UI.WebControls.Button cadastrar;
		
		protected System.Web.UI.WebControls.Button cancelar;
		
		protected System.Web.UI.WebControls.View aba2;
		
		protected System.Web.UI.WebControls.GridView tabela;
		
		protected System.Web.UI.WebControls.LinkButton edit;
		
		protected System.Web.UI.WebControls.LinkButton del;
		
		protected System.Web.UI.WebControls.View aba3;
		
		protected System.Web.UI.WebControls.DropDownList dropPessoa;
		
		protected System.Web.UI.WebControls.RadioButtonList listaTransporte;
		
		protected System.Web.UI.WebControls.Panel panel1;
		
		protected System.Web.UI.WebControls.TextBox milhas;
		
		protected System.Web.UI.WebControls.TextBox valorMilha;
		
		protected System.Web.UI.WebControls.Panel panel2;
		
		protected System.Web.UI.WebControls.TextBox km;
		
		protected System.Web.UI.WebControls.TextBox valorKm;
		
		protected System.Web.UI.WebControls.DropDownList dropEstOrigem;
		
		protected System.Web.UI.WebControls.DropDownList dropCidOrigem;
		
		protected System.Web.UI.WebControls.DropDownList dropEstDestino;
		
		protected System.Web.UI.WebControls.DropDownList dropCidDestino;
		
		protected System.Web.UI.WebControls.LinkButton cadastrarTransporte;
		
		protected System.Web.UI.WebControls.LinkButton cancelarTransporte;
		
		protected System.Web.UI.WebControls.GridView tabelaTransporte;
	}
}
